"""
message_builder.py
Tạo Lark Interactive Card đẹp, nhóm task theo assignee.
Mỗi assignee có màu riêng. Status hiển thị bằng badge màu.
"""

from datetime import date


# Màu đại diện cho từng assignee (tự động assign theo thứ tự xuất hiện)
ASSIGNEE_COLORS = [
    "#2D7EFF",   # blue
    "#7B61FF",   # purple
    "#00B0A6",   # teal
    "#FF6B2B",   # orange
    "#E8283C",   # red
    "#00875A",   # green
    "#FF8B00",   # amber
    "#FF4F9B",   # pink
]

STATUS_CONFIG = {
    "done":        {"label": "Done",        "color": "#00B0A6"},
    "in_progress": {"label": "In progress", "color": "#FF8B00"},
    "todo":        {"label": "To do",       "color": "#888888"},
    "not_found":   {"label": "Not found",   "color": "#CCCCCC"},
}


def build_weekly_report_card(
    tasks: list[dict],
    week_start: date,
    week_end: date,
) -> dict:
    """
    Tạo Lark Interactive Card JSON.
    https://open.larksuite.com/document/ukTMukTMukTM/uAjNwUjLwYDM14CM2ATN
    """
    # Nhóm task theo assignee
    assignees: dict[str, list[dict]] = {}
    for t in tasks:
        name = t.get("assignee") or "Unknown"
        assignees.setdefault(name, []).append(t)

    # Map assignee → màu
    color_map: dict[str, str] = {}
    for i, name in enumerate(assignees):
        color_map[name] = ASSIGNEE_COLORS[i % len(ASSIGNEE_COLORS)]

    # Tổng hợp số liệu
    total       = len(tasks)
    done_count  = sum(1 for t in tasks if t.get("status") == "done")
    wip_count   = sum(1 for t in tasks if t.get("status") == "in_progress")
    todo_count  = sum(1 for t in tasks if t.get("status") in ("todo", "not_found"))

    # ── Header ───────────────────────────────────────────────────────────────
    header = {
        "template": "blue",
        "title": {
            "tag": "plain_text",
            "content": f"📋  Weekly Report  {week_start.strftime('%d/%m')} – {week_end.strftime('%d/%m/%Y')}",
        },
    }

    elements: list[dict] = []

    # ── Summary stats ────────────────────────────────────────────────────────
    elements.append({
        "tag": "column_set",
        "flex_mode": "stretch",
        "columns": [
            _stat_col("Total", str(total),       "#2D7EFF"),
            _stat_col("Done",  str(done_count),  "#00B0A6"),
            _stat_col("WIP",   str(wip_count),   "#FF8B00"),
            _stat_col("To do", str(todo_count),  "#888888"),
        ],
    })

    elements.append({"tag": "hr"})

    # ── Mỗi assignee 1 section ───────────────────────────────────────────────
    for assignee, a_tasks in assignees.items():
        color = color_map[assignee]

        # Header assignee
        elements.append({
            "tag": "markdown",
            "content": f"**<font color='{color}'>{assignee}</font>**  "
                       f"`{len(a_tasks)} task{'s' if len(a_tasks) > 1 else ''}`",
        })

        # Từng task
        for t in a_tasks:
            status_cfg = STATUS_CONFIG.get(t.get("status", "todo"), STATUS_CONFIG["todo"])
            due_text   = f"  ·  Due {t['due']}" if t.get("due") else ""
            name       = t.get("name") or "(no name)"

            # Truncate tên dài
            if len(name) > 60:
                name = name[:57] + "..."

            elements.append({
                "tag": "markdown",
                "content": (
                    f"<font color='{status_cfg['color']}'>"
                    f"● {status_cfg['label']}"
                    f"</font>  "
                    f"{name}"
                    f"<font color='#999999'>{due_text}</font>"
                ),
            })

        elements.append({"tag": "hr"})

    # Xóa hr cuối cùng
    if elements and elements[-1].get("tag") == "hr":
        elements.pop()

    # ── Footer ───────────────────────────────────────────────────────────────
    elements.append({
        "tag": "note",
        "elements": [{
            "tag": "plain_text",
            "content": f"Generated by Lark Weekly Bot · {date.today().strftime('%A, %d %b %Y')}",
        }],
    })

    return {
        "msg_type": "interactive",
        "card": {
            "header":   header,
            "elements": elements,
        },
    }


def _stat_col(label: str, value: str, color: str) -> dict:
    """Tạo 1 cột stat nhỏ trong summary row."""
    return {
        "tag": "column",
        "elements": [
            {
                "tag": "markdown",
                "content": (
                    f"<font color='{color}'>**{value}**</font>\n"
                    f"<font color='#999999'>{label}</font>"
                ),
                "text_align": "center",
            }
        ],
    }
